'use strict';
/**
 * CHK_ID → 한글 제목 매핑.
 * v1 mock.js _inferTitle 의 titles 객체를 그대로 이관 (변경 없음).
 */
module.exports = {
  // Linux
  'os-linux-25': 'passwd 파일 점검',
  'os-linux-34': 'cron 디렉토리 권한 (/var/spool/cron)',
  'os-linux-41': 'sendmail PrivacyOptions',
  'os-linux-61': 'inetd/xinetd 불필요 서비스',
  'os-linux-84': 'UID 0 다중 계정 점검',
  'os-linux-188': 'vsftpd Anonymous 접속 차단',
  'os-linux-207': 'PATH 환경변수 보안',
  'os-linux-227': 'UID 중복 확인',
  'os-linux-237': '불필요 프로세스 확인',
  'os-linux-254': 'TCP Wrapper (hosts.allow/deny)',
  'os-linux-271': 'PAM faillock (계정 잠금 임계값)',
  'os-linux-273': '/sbin/dump SUID 권한',
  'os-linux-279': 'login.defs GID_MIN (사용자 그룹 분리)',
  'os-linux-285': '관리자 외 root 그룹 차단',
  'os-linux-286': 'NFS 서비스 비활성화',
  'os-linux-289': 'vsftpd user_list (FTP 사용자 제한)',
  'os-linux-293': 'BIND DNS 버전 정보 노출',
  'os-linux-306': 'NFS 접근 통제 (/etc/exports)',
  'os-linux-318': '로그온 경고 메시지 (motd/banner)',
  'os-linux-320': '/etc/shadow 파일 권한',
  'os-linux-324': 'sendmail.cf 설정',
  'os-linux-335': 'sendmail VRFY/EXPN 차단',
  'os-linux-337': 'sendmail 버전 정보',
  'os-linux-338': 'sendmail 릴레이 제한',
  'os-linux-340': 'vsftpd ftpusers (root FTP 차단)',
  'os-linux-341': '.netrc 파일 권한',
  'os-linux-342': 'r-command (rsh/rlogin) 차단',
  'os-linux-344': '세션 TIMEOUT (TMOUT)',
  'os-linux-361': 'BIND version 정보 숨김',
  'os-linux-362': 'BIND recursion 제한',
  'os-linux-363': 'BIND Zone Transfer 제한',
  'os-linux-365': '/etc/rc.d/init.d 디렉토리 권한',
  'os-linux-367': '/usr 디렉토리 권한',
  'os-linux-369': 'syslog 설정 정보',
  'os-linux-374': '로그 파일 권한 (/var/log)',
  'os-linux-377': 'login.defs 패스워드 정책',
  'os-linux-378': 'root umask 설정',
  'os-linux-379': '/etc/inittab 권한',
  'os-linux-380': 'cron.allow/cron.deny 권한',
  'os-linux-381': '/etc/hosts.equiv 점검',
  'os-linux-383': 'root 원격 접속 제한 (securetty/PAM)',
  'os-linux-386': 'cron 참조 파일 Other Write 권한',
  'os-linux-389': '설치 패키지 리스트 (rpm -qa)',
  'os-linux-440': '컴파일러 권한 (cc/gcc)',
  'os-linux-1922': 'syslog LogLevel 설정',
  'os-linux-1973': 'finger 서비스 비활성화',
  'os-linux-1998': '사용자 환경파일 권한 (.profile 등)',
  'os-linux-2289': 'PAM su 제한 (wheel 그룹)',
  'os-linux-2369': '사용자 umask 설정',
  'os-linux-2389': 'Anonymous FTP 차단',
  'os-linux-2498': 'SNMP V3 기본 community 점검',
  'os-linux-2576': '홈 디렉토리 소유자 일치',
  'os-linux-2581': 'auth syslog 설정',
  'os-linux-2586': '시스템 계정 shell (nologin)',
  'os-linux-2596': 'DNS 서비스 실행 여부',
  'os-linux-2688': '불필요 데몬 프로세스',
  'os-linux-2778': 'proftpd allow 설정',
  'os-linux-2784': 'cron syslog 기록',
  'os-linux-2788': 'BIND Dynamic Update 비활성',
  'os-linux-2790': 'SMTP 배너 정보 노출',
  'os-linux-2793': 'proftpd ServerIdent (FTP 배너)',
  'os-linux-3072': 'sudo 권한 사용자 점검',
  'os-linux-3076': 'OS 종류/버전 정보',
  'os-linux-3077': 'snmpd.conf 설정',

  // Windows
  'os-win-49': 'TlntSvr 서비스 (Telnet)',
  'os-win-56': 'shutdownwithoutlogon',
  'os-win-59': 'LimitBlankPasswordUse',
  'os-win-60': 'NTLMv2 응답 설정 (LmCompatibilityLevel)',
  'os-win-64': 'RequireSignOrSeal (Netlogon)',
  'os-win-65': 'AddPrinterDrivers',
  'os-win-139': '공유 자원 ACL 정보',
  'os-win-150': 'OS 시스템 정보',
  'os-win-152': '마지막 로그온 사용자 표시 제어',
  'os-win-154': '화면 보호기 설정 (SCRNSAVE)',
  'os-win-156': '로그온 경고 메시지 (legalnoticecaption)',
  'os-win-157': '파일 시스템 정보',
  'os-win-160': 'SMTPSVC 서비스 (SMTP)',
  'os-win-180': 'DNS Recursive Query',
  'os-win-186': 'SeBackupPrivilege (백업 권한)',
  'os-win-188': 'SeNetworkLogonRight (네트워크 로그온 권한)',
  'os-win-263': 'Eventlog RestrictGuestAccess',
  'os-win-267': 'MSFTPSVC IPSECURITY',
  'os-win-268': 'restrictanonymous (익명 접근 제한)',
  'os-win-282': 'DNS SecureSecondaries',
  'os-win-284': 'Administrator 계정명 변경',
  'os-win-285': 'Administrators 그룹 점검',
  'os-win-286': 'ClearTextPassword',
  'os-win-287': '사용자 계정 정보',
  'os-win-289': 'SAM 파일 권한',
  'os-win-291': 'crashonauditfail',
  'os-win-295': 'SeTakeOwnershipPrivilege',
  'os-win-296': 'AllocateDASD',
  'os-win-297': 'MSFTPSVC SERVER_STATUS',
  'os-win-298': 'Everyone 공유 자원',
  'os-win-300': 'RemoteRegistry 서비스',
  'os-win-301': 'AutoAdminLogon',
  'os-win-306': 'Windows Firewall 활성',
  'os-win-361': 'W32Time NTP 서버 유형',
  'os-win-418': 'everyoneincludesanonymous',
  'os-win-421': 'LSAAnonymousNameLookup',
  'os-win-423': '사용자 그룹 정보',
  'os-win-425': 'IIS Anonymous Auth',
  'os-win-426': '터미널 서비스 MinEncryptionLevel',
  'os-win-428': 'SNMP 접근 통제',
  'os-win-429': 'TlntSvr 서비스 (Telnet 활성)',
  'os-win-432': '예약 작업 상태',
  'os-win-438': 'enableforcedlogoff',
  'os-win-440': '사용자 홈 디렉터리 권한',
  'os-win-443': 'SeInteractiveLogonRight',
  'os-win-444': '시작프로그램',
  'os-win-446': 'EFS 서비스 상태',
  'os-win-448': 'SNMP 서비스 상태',
  'os-win-452': 'Alerter 서비스 (NetBIOS)',
  'os-win-484': 'AutoShareServer',
  'os-win-486': '계정 잠금 임계값 (LockoutBadCount)',
  'os-win-487': 'V3 백신 상태',
  'os-win-489': '백신 설치/실행 상태',
  'os-win-494': 'NT 이벤트 로그 정책',
  'os-win-495': '최소 비밀번호 길이',
  'os-win-526': 'IIS FTP Everyone 권한',
  'os-win-1993': '이벤트 로그 디렉토리 권한',
  'os-win-2503': '사용자 계정 비밀번호 변경 주기',
  'os-win-2508': 'OLE LegacyAuthenticationLevel',
  'os-win-2582': 'SynAttackProtect',
  'os-win-2588': 'SMTP_HIDE_BANNER',
  'os-win-2589': 'FTP_HIDE_BANNER',
  'os-win-2590': 'DNS Zones AllowUpdate',
  'os-win-2591': 'DNS 서비스 상태',
  'os-win-2592': '시스템 이벤트 감사 정책',
  'os-win-2597': 'RDP MaxIdleTime (세션 타임아웃)',
  'os-win-2789': '$Recycle.Bin 권한',
  'os-win-2985': 'SSH 개인키 패스프레이즈',
  'os-win-4635': 'OS 종류 정보',
};
